
package interface_type;
public interface Transport2{
    /*
     * FIRST OF ALL CREATE INTERFACE
     * IN INTERFACE ALL METHODS ARE PUBLIC ABSTRACT DECALRED
     * THEN CREATE ANOTHER CHILD CLASS TO EXTEND THE INTERFACE
     * BUT ALWAYS REMEMBER CHILD CLASS NEED TO INTIALIZE THE PUBLIC ABSTRACT METHOD DECALRED IN INTERFACE
     * IN INTERFACE WE HAVE VARIABLES TOO BUT THEY ARE FINAL AND STATIC
     * INTERFACE BASICALLY USED FOR METHODS
     * IF CHILD CLASS THAT IS EXTENDING INTERFACE NOT ABLE TO INTIALIZE PUBLIC ABSTRACT METHODS OF INTERFACE THEN IT DECLARE ITSELF AS ABSTRACT CLASS
     * AND THEN THAT ROLE WILL BE PASSED TO IT NEXT CHILD CLASS 
     */
    public int fuel=60;
    public abstract void getsetgo2();

    
}
