package challenge2;
public interface  Flyable {

    /*
     * CREATE AN INTERFACE FLYABLE AND CREATE ABSTRACT METHOD IN IT FOR FLY
     * CREATE SUBCLASS BIRD THAT EXTENDS INTERFACE FLYABLE AND MAKE IT ABSTRACT CLASS AS IT IS NOT INITIALIZING FLY METHOD
     * CREATE SUBCLASS EAGLE AS A CHILD CLASS THAT EXTENDS ABSTRACT CLASS BIRD AND INITIALIZE ABSTRACT METHOD FLY
     */
    public abstract void fly();
    
}
