
import java.util.*;

public class Lec10 {
    // PRINT ALL FIBONAACI SERIES TILL N

    public static void main(String[] args) {
        /*
        SUMMARY
        This Java program generates and prints the Fibonacci series up to a specified number of terms (N), based on user input.

        📌 Key Features:
        1.)Takes an integer input range from the user which determines how many terms of the Fibonacci series to print.

        2.)Initializes the first two Fibonacci numbers: 0 and 1 
        3.)Uses a for loop to calculate and print the next Fibonacci number in the sequence for N terms.

        4.)Each number is generated by adding theA previous two numbers.
         */
        Scanner input = new Scanner(System.in);
        System.out.print("PLEASE ENTER THE RANGE:- ");
        int range = input.nextInt();

        int next;
        int i = 0;
        int j = 1;
        // System.out.println(i);
        // System.out.println(j);
        for (int k = 0; k < range; k++) {
            System.out.println(i);
            next = i + j;
            i = j;
            j = next;

        }
    }

}
